export const coinList = [
  "art",
  "aNEAR",
  "aBTC",
  "aGOLD",
  "aSPY",
  "aEUR",
  "aGOOG",
  "aTSLA",
  "aNFLX",
  "aAAPL",
  "aFB",
  "a-xBTC",
  "a-2xBTC",
  "a-3xBTC",
  "a-5xBTC",
  "a-10xBTC",
  "a2xBTC",
  "a3xBTC",
  "a5xBTC",
  "a10xBTC",
];

export let initialState_null_dash = {
  art: null,
  aNEAR: null,
  aBTC: null,
  aGOLD: null,
  aSPY: null,
  aEUR: null,
  aGOOG: null,
  aTSLA: null,
  aNFLX: null,
  aAAPL: null,
  aFB: null,
  "a-xBTC": null,
  "a-2xBTC": null,
  "a-3xBTC": null,
  "a-5xBTC": null,
  "a-10xBTC": null,
  a2xBTC: null,
  a3xBTC: null,
  a5xBTC: null,
  a10xBTC: null,
};

export let initialState_null = {
  art: null,
  aNEAR: null,
  aBTC: null,
  aGOLD: null,
  aSPY: null,
  aEUR: null,
  aGOOG: null,
  aTSLA: null,
  aNFLX: null,
  aAAPL: null,
  aFB: null,
  "a-xBTC": null,
  "a-2xBTC": null,
  "a-3xBTC": null,
  "a-5xBTC": null,
  "a-10xBTC": null,
  a2xBTC: null,
  a3xBTC: null,
  a5xBTC: null,
  a10xBTC: null,
};

export let initialState_null_week = {
  art: null,
  aNEAR: null,
  aBTC: null,
  aGOLD: null,
  aSPY: null,
  aEUR: null,
  aGOOG: null,
  aTSLA: null,
  aNFLX: null,
  aAAPL: null,
  aFB: null,
  "a-xBTC": null,
  "a-2xBTC": null,
  "a-3xBTC": null,
  "a-5xBTC": null,
  "a-10xBTC": null,
  a2xBTC: null,
  a3xBTC: null,
  a5xBTC: null,
  a10xBTC: null,
};

export let initialState_null_month = {
  art: null,
  aNEAR: null,
  aBTC: null,
  aGOLD: null,
  aSPY: null,
  aEUR: null,
  aGOOG: null,
  aTSLA: null,
  aNFLX: null,
  aAAPL: null,
  aFB: null,
  "a-xBTC": null,
  "a-2xBTC": null,
  "a-3xBTC": null,
  "a-5xBTC": null,
  "a-10xBTC": null,
  a2xBTC: null,
  a3xBTC: null,
  a5xBTC: null,
  a10xBTC: null,
};

export let initialState_zero_price = {
  art: "0",
  aNEAR: "0",
  aBTC: "0",
  aGOLD: "0",
  aSPY: "0",
  aEUR: "0",
  aGOOG: "0",
  aTSLA: "0",
  aNFLX: "0",
  aAAPL: "0",
  aFB: "0",
  "a-xBTC": "0",
  "a-2xBTC": "0",
  "a-3xBTC": "0",
  "a-5xBTC": "0",
  "a-10xBTC": "0",
  a2xBTC: "0",
  a3xBTC: "0",
  a5xBTC: "0",
  a10xBTC: "0",
};

export let initialState_zero_balance = {
  art: "0",
  aNEAR: "0",
  aBTC: "0",
  aGOLD: "0",
  aSPY: "0",
  aEUR: "0",
  aGOOG: "0",
  aTSLA: "0",
  aNFLX: "0",
  aAAPL: "0",
  aFB: "0",
  "a-xBTC": "0",
  "a-2xBTC": "0",
  "a-3xBTC": "0",
  "a-5xBTC": "0",
  "a-10xBTC": "0",
  a2xBTC: "0",
  a3xBTC: "0",
  a5xBTC: "0",
  a10xBTC: "0",
};

export const API_URL = "https://api.artcoin.network/prices";
